security:
  oauth2:
    client:
      client-id: 64aed7c0511e9cae08bb
      client-secret: 91df0c4f21cd363a4d1be6837a04c2d7f885f4eb
      
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false
  